apiVersion: v1
kind: Service
metadata:
  name: tawazun-service
spec:
  selector:
    app: golden-k8s
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30004